//========================
// 
//========================
$(document).ready(function() {
    
	$(document).bind("click",function(e){
		var target  = $(e.target);
		if(target.parents(".nav").size()==0){
			window.top.$(".opened").removeClass("opened");
		}
	});
	var labelBottomDiv = "<div id='labelBottomDiv' style='width: 230px; display :none; position: fixed;bottom: 0;left:0px;right:0px;z-index:1000;margin-left:auto;margin-right:auto;'> <a style='' href='###' class='btn_05' onclick='SaveRecord();'>保存<b></b></a><a style='' href='###' class='btn_05' onclick='window.location.reload()'>取消<b></b></a></div>";
	$(".label_div").append(labelBottomDiv); 
	$(".label_text,.label_textarea").bind('keydown', function() {
		if(this.readOnly==false){
			 $("#labelBottomDiv").css("display","");
		}

	});
  
	   $(".TreeClass").css("height",$(".page_content").height());

      });
function showLabelBottomDiv(){
	 $("#labelBottomDiv").css("display","");
}
function CheckAll(parentCheckBox,checkboxname)
{
	var participants = document.getElementsByTagName("input");
    //alert(parentCheckBox);
	for ( var i=0; i < participants.length; i++ ) 
	{
		if(participants[i].name.indexOf(checkboxname)!=-1 && !participants[i].disabled)
		{				
			var participant = participants[i];
			if ( participant != null ) {
				participant.checked = parentCheckBox.checked;
			}
		}
	}
}

function OpenDialog(Url,Width,Height)
{
	var strFeatures="dialogWidth="+ Width +"px;dialogHeight="+ Height +"px;center=yes;middle=yes ;help=no;status=no";
	var today=new Date();
	if(Url.indexOf("?")!=-1)
	{
		Url+="&Time="+today.getMinutes()+"_"+today.getMilliseconds();
	}
	else
	{
		Url+="?Time="+today.getMinutes()+"_"+today.getMilliseconds();
	}
	var WindowResult= window.showModalDialog(Url,'',strFeatures); 
	return WindowResult;
}

function getCenterLocation(width, height){
	var location = {};
	var ah = screen.availHeight;
	var aw = screen.availWidth;
	var xc = (aw - width) / 2;
	var yc = (ah - height) / 2;
	location.top = yc;
	location.left = xc;
	return location;
}

function OpenDialog_Param(Url,Param,Width,Height)
{
	var strFeatures="dialogWidth="+ Width +"px;dialogHeight="+ Height +"px;center=yes;middle=yes ;help=no;status=no";
	var today=new Date();
	if(Url.indexOf("?")!=-1)
	{
		Url+="&Time="+today.getMinutes()+"_"+today.getMilliseconds();
	}
	else
	{
		Url+="?Time="+today.getMinutes()+"_"+today.getMilliseconds();
	}
	var WindowResult= window.showModalDialog(Url,Param,strFeatures); 
	return WindowResult;
}
function remove_all_option(object){
	var length = object.options.length;
	for(var i=length-1;i>=0;i--){
		object.options.remove(i);
	}
}

function add_option(sel,txt,val,position){
	if(val==""||txt=="")
		return false;
	for(i=0;i<sel.options.length;i++){
		if(val==sel.options[i].value){
			alert("This option "+txt+" exists!");
			return false;
		}
	}
	
	if(position==null||position>sel.options.length){
		var option = new Option(txt,val);
		sel.options[sel.options.length] = option;
	}
	else{
		var option = document.createElement("option"); 
		option.value = val; 
		option.innerText = txt; 
		sel.insertBefore(option, sel.options[position-1]);		
	}
}

function del_option(sel){
	sel.options.remove(sel.selectedIndex);
}

function popupCenter(url, name, width, height, menubar, toolbar, location, resize, scroll,status) {
    var str = "height=" + height + ",innerHeight=" + height;
    str += ",width=" + width + ",innerWidth=" + width;
    if (window.screen) {
		var ah = screen.availHeight - 30;
		var aw = screen.availWidth - 10;
		var xc = (aw - width) / 2;
		var yc = (ah - height) / 2;
		str += ",left=" + xc + ",screenX=" + xc;
		str += ",top=" + yc + ",screenY=" + yc;
    }
    str+= ",menubar="+menubar+",toolbar="+toolbar+",location="+location+",resizable=no,scrollbars="+scroll+",status="+status;
    var win= window.open(url, name, str);

    try {
        win.focus();
    }
    	catch (ex) {
    }
    return win;
}

function createWindow(divName,title,left,top,width,height,href){
	var top = window;
	var i = 0;
	while($(top.document).find("#newWindow").length==0){
		top = top.parent;
		i++;
		if(i>6){
			alert("break");
			break;
		}
	}
	if($(top.document).find("#"+divName).length==0){
		var div = "<div id='"+divName+"' class='easyui-window' closed='true'>"+
		"<iframe id='"+divName+"_frm' width='"+width+"px' scrolling='no' frameborder='0' style='margin-top: -6px !important;margin-left: -6px !important;width: "+width+"px; height: "+height+"px;' onload='autoAdjust(\""+title+"\",\""+divName+"\", \""+divName+"_frm\")'></iframe>"+
	    "</div>";
	    $(top.document.body).append(div);
	}
	top.$("#"+divName).window({
		title: 			title,
		left: 			left,
		top:			top,
		width:			width,
		height:			height,
		minimizable: false
	});
	top.$("#"+divName+"_frm").attr("src",href);
	top.$("#"+divName).window('refresh');
	top.$("#"+divName).window('open');
}


function createSimpleWindow(divName, title, href, width, height){
    /**
	var ah = screen.availHeight - 30;
	var aw = screen.availWidth - 10;
	var left = (aw - width) / 2;
	var top1 = (ah - height) / 2;
	*/
	var location = getCenterLocation(width, height);
	var left = location.left;
	var top1 = location.top;
	
	var top = window;
	var i = 0;
	while($(top.document).find("#newWindow").length==0){
		top = top.parent;
		i++;
		if(i>6){
			alert("break");
			break;
		}
	}
	if($(top.document).find("#"+divName).length==0){
		var div = "<div id='"+divName+"'  class='easyui-window' closed='true'>";
		if(!width || !height)
		    div += "<iframe id='"+divName+"_frm' scrolling='no' frameborder='0' style='width: 100%; height: 100%;' onload='autoAdjust(\""+title+"\", \""+divName+"\", \""+divName+"_frm\")'></iframe>";
	    else
	        div += "<iframe id='"+divName+"_frm' scrolling='no' frameborder='0' style='width: 100%; height: 100%;' ></iframe>"
	    div += "</div>";
	    $(top.document.body).append(div);
	}
	if(!width || !height){
	    
	}else{
	    top.$("#"+divName).window({
		    title: 			title,
		    //left: 			left,
		    //top:			top1,
		    width:			width,
		    height:			height,
		    minimizable: false,
		    onBeforeClose:function(){
		        
			    top.close_win(divName);
		    }
	    });
	}
	
	top.$("#"+divName+"_frm").attr("src",href);
	top.$("#"+divName).window('refresh');
	if(width && height)
	    top.$("#"+divName).window('open');
}


function openWindow(divName, title, left, top, width, height, href, resizable, 
					collapsible, maximizable, minimizable, closable,iframeName){
	if(iframeName!=null){
		$('#'+divName).window({
			title: 			title,
			left: 			left,
			top:			top,
			width:			width,
			height:			height,
			//href:			href,
			resizable:		true,
			collapsible:	collapsible,
			maximizable:	maximizable,
			minimizable:	minimizable,
			closable:		closable
		});
		$("#"+iframeName).attr("src",href);
	}else{
		$('#'+divName).window({
			title: 			title,
			left: 			left,
			top:			top,
			width:			width,
			height:			height,
			href:			href,
			resizable:		true,
			collapsible:	collapsible,
			maximizable:	maximizable,
			minimizable:	minimizable,
			closable:		closable
		});
	}
	$('#'+divName).window('refresh');
	$('#'+divName).window('open');
	
}
function openparentWindow(divName, title, left, top, width, height, href, resizable, 
		collapsible, maximizable, minimizable, closable,iframeName){
	var divDom=$("#"+divName);
	if(iframeName!=null)
   		var iframeDom=$("#"+iframeName);
	var divParent=parent;
	var i=0;
	while(divDom.size()==0&&i<=5){
		divDom=$("#"+divName,divParent.document);
		if(iframeName!=null)
			iframeDom=$("#"+iframeName,divParent.document);
		divParent=divParent.parent;
		i=i+1;
	}
    if(iframeName!=null){
    	divParent.$("#"+iframeName).attr("src","");
    	divParent.$("#"+divName).window({
    		title:title,
    		left:left,
    		top:top,
    		width:width,
    		height:height,
			resizable:true,
			onBeforeClose:function(){
			    divParent.close_win(divName);
		    }
    	});
    	divParent.$("#"+iframeName).attr("src",href);
    }else{
    	divParent.$("#"+divName).window({
    		title:title,
    		left:left,
    		top:top,
    		width:width,
    		height:height,
    	    resizable:true
    	});
    	divParent.$("#"+divName).window('refresh');
    }
	divParent.$("#"+divName).window('open');
}
  
  function getPageSize(){
    var xScroll, yScroll;
    if (window.innerHeight && window.scrollMaxY) { 
      xScroll = document.body.scrollWidth;
      yScroll = window.innerHeight + window.scrollMaxY;
    } else if (
      document.body.scrollHeight > document.body.offsetHeight){ // all but Explorer Mac
      xScroll = document.body.scrollWidth;
      yScroll = document.body.scrollHeight;
    } else { // Explorer Mac...would also work in Explorer 6 Strict, Mozilla and Safari
      xScroll = document.body.offsetWidth;
      yScroll = document.body.offsetHeight;
    }
    
    var windowWidth, windowHeight;
    if (self.innerHeight) { // all except Explorer
      windowWidth = self.innerWidth;
      windowHeight = self.innerHeight;
    } else if (
      document.documentElement && document.documentElement.clientHeight) { // Explorer 6 Strict Mode
      windowWidth = document.documentElement.clientWidth;
      windowHeight = document.documentElement.clientHeight;
    } else if (document.body) { // other Explorers
      windowWidth = document.body.clientWidth;
      windowHeight = document.body.clientHeight;
    } 
    
    // for small pages with total height less then height of the viewport
    if(yScroll < windowHeight){
      pageHeight = windowHeight;
    } else { 
      pageHeight = yScroll;
    }
    
    // for small pages with total width less then width of the viewport
    if(xScroll < windowWidth){ 
      pageWidth = windowWidth;
    } else {
      pageWidth = xScroll;
    }
    
    arrayPageSize = new Array(pageWidth,pageHeight,windowWidth,windowHeight);
    return arrayPageSize;
  }
  
  function locate_center(obj){    
      var arrayPageSize = getPageSize();
      var objleft, objtop, left, top; 
      objleft = obj.style.width.substring(0,obj.style.width.length-2);
      objtop = obj.style.height.substring(0,obj.style.height.length-2);
      if(objleft<arrayPageSize[0])
        left = (arrayPageSize[0]-objleft)/2;
      if(objtop<arrayPageSize[1])
        top = (arrayPageSize[1]-objtop)/2;
      obj.style.left = left;
	  obj.style.top = top;	  
  }
  
  function formatDate(v){  
	  if(typeof v == 'string') v = parseDate(v);  
	  if(v instanceof Date){  
	    var y = v.getFullYear();  
	    var m = v.getMonth() + 1;  
	    var d = v.getDate();  
	    var h = v.getHours();  
	    var i = v.getMinutes();  
	    var s = v.getSeconds();  
	    var ms = v.getMilliseconds();     
	    if(ms>0) return y + '-' + m + '-' + d + ' ' + h + ':' + i + ':' + s + '.' + ms;  
	    if(h>0 || i>0 || s>0) return y + '-' + m + '-' + d + ' ' + h + ':' + i + ':' + s;  
	    return y + '-' + m + '-' + d;  
	  }  
	  return '';  
	}  
  
  function getAppUrl(){
	  var url = window.location.href;
	  var port = window.location.port;
	  var pos = url.indexOf(port);
	  var server = url.substr(0,parseInt(pos+port.length+1));
	  var url1 = url.substr(parseInt(pos+port.length)+1,url.length);
	  pos = url1.indexOf("\/");
	  url1 = url1.substr(0,pos);
	  url = server + url1;
      return url;
  }
  function OpenWin(Url,Width,Height){
  var loc_x=(screen.availWidth-parseInt(Width))/2;
  var loc_y=(screen.availHeight-parseInt(Height))/2;
  
	var Feature='Width='+ Width +',Height='+ Height +',Left='+ loc_x +',Top='+ loc_y +',help:no,status:no,scrollbars=yes,resizable=yes';
	var win=window.open(Url,'',Feature);
	win.focus();
}

function makePy(str)
{
	if (typeof (str) != "string")
	{
		return str;
	}
	var arrResult = new Array();
	for ( var i = 0, len = str.length; i < len; i++)
	{
		var ch = str.charAt(i);
		arrResult.push(checkCh(ch));
	}
	var resarr = mkRslt(arrResult);
	// return resarr.join("").toLowerCase();
	return resarr.join("").toUpperCase();
}

function checkCh(ch)
{
	var uni = ch.charCodeAt(0);
	if (uni > 40869 || uni < 19968)
		return ch; // dealWithOthers(ch);
	return (oMultiDiff[uni] ? oMultiDiff[uni] : (strChineseFirstPY.charAt(uni - 19968)));
}
function mkRslt(arr)
{
	var arrRslt =
	[ "" ];
	for ( var i = 0, len = arr.length; i < len; i++)
	{
		var str = arr[i];
		var strlen = str.length;
		if (strlen == 1)
		{
			for ( var k = 0; k < arrRslt.length; k++)
			{
				arrRslt[k] += str;
			}
		} else
		{
			var tmpArr = arrRslt.slice(0);
			arrRslt = [];
			for (k = 0; k < strlen; k++)
			{
				var tmp = tmpArr.slice(0);
				for ( var j = 0; j < tmp.length; j++)
				{
					tmp[j] += str.charAt(k);
				}
				arrRslt = arrRslt.concat(tmp);
			}
		}
	}
	return arrRslt;
}
var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
var oMultiDiff =
{
	"19969" : "DZ",
	"19975" : "WM",
	"19988" : "QJ",
	"20048" : "YL",
	"20056" : "SC",
	"20060" : "NM",
	"20094" : "QG",
	"20127" : "QJ",
	"20167" : "QC",
	"20193" : "YG",
	"20250" : "KH",
	"20256" : "ZC",
	"20282" : "SC",
	"20285" : "QJG",
	"20291" : "TD",
	"20314" : "YD",
	"20340" : "NE",
	"20375" : "TD",
	"20389" : "YJ",
	"20391" : "CZ",
	"20415" : "PB",
	"20446" : "YS",
	"20447" : "SQ",
	"20504" : "TC",
	"20608" : "KG",
	"20854" : "QJ",
	"20857" : "ZC",
	"20911" : "PF",
	"20504" : "TC",
	"20608" : "KG",
	"20854" : "QJ",
	"20857" : "ZC",
	"20911" : "PF",
	"20985" : "AW",
	"21032" : "PB",
	"21048" : "XQ",
	"21049" : "SC",
	"21089" : "YS",
	"21119" : "JC",
	"21242" : "SB",
	"21273" : "SC",
	"21305" : "YP",
	"21306" : "QO",
	"21330" : "ZC",
	"21333" : "SDC",
	"21345" : "QK",
	"21378" : "CA",
	"21397" : "SC",
	"21414" : "XS",
	"21442" : "SC",
	"21477" : "JG",
	"21480" : "TD",
	"21484" : "ZS",
	"21494" : "YX",
	"21505" : "YX",
	"21512" : "HG",
	"21523" : "XH",
	"21537" : "PB",
	"21542" : "PF",
	"21549" : "KH",
	"21571" : "E",
	"21574" : "DA",
	"21588" : "TD",
	"21589" : "O",
	"21618" : "ZC",
	"21621" : "KHA",
	"21632" : "ZJ",
	"21654" : "KG",
	"21679" : "LKG",
	"21683" : "KH",
	"21710" : "A",
	"21719" : "YH",
	"21734" : "WOE",
	"21769" : "A",
	"21780" : "WN",
	"21804" : "XH",
	"21834" : "A",
	"21899" : "ZD",
	"21903" : "RN",
	"21908" : "WO",
	"21939" : "ZC",
	"21956" : "SA",
	"21964" : "YA",
	"21970" : "TD",
	"22003" : "A",
	"22031" : "JG",
	"22040" : "XS",
	"22060" : "ZC",
	"22066" : "ZC",
	"22079" : "MH",
	"22129" : "XJ",
	"22179" : "XA",
	"22237" : "NJ",
	"22244" : "TD",
	"22280" : "JQ",
	"22300" : "YH",
	"22313" : "XW",
	"22331" : "YQ",
	"22343" : "YJ",
	"22351" : "PH",
	"22395" : "DC",
	"22412" : "TD",
	"22484" : "PB",
	"22500" : "PB",
	"22534" : "ZD",
	"22549" : "DH",
	"22561" : "PB",
	"22612" : "TD",
	"22771" : "KQ",
	"22831" : "HB",
	"22841" : "JG",
	"22855" : "QJ",
	"22865" : "XQ",
	"23013" : "ML",
	"23081" : "WM",
	"23487" : "SX",
	"23558" : "QJ",
	"23561" : "YW",
	"23586" : "YW",
	"23614" : "YW",
	"23615" : "SN",
	"23631" : "PB",
	"23646" : "ZS",
	"23663" : "ZT",
	"23673" : "YG",
	"23762" : "TD",
	"23769" : "ZS",
	"23780" : "QJ",
	"23884" : "QK",
	"24055" : "XH",
	"24113" : "DC",
	"24162" : "ZC",
	"24191" : "GA",
	"24273" : "QJ",
	"24324" : "NL",
	"24377" : "TD",
	"24378" : "QJ",
	"24439" : "PF",
	"24554" : "ZS",
	"24683" : "TD",
	"24694" : "WE",
	"24733" : "LK",
	"24925" : "TN",
	"25094" : "ZG",
	"25100" : "XQ",
	"25103" : "XH",
	"25153" : "PB",
	"25170" : "PB",
	"25179" : "KG",
	"25203" : "PB",
	"25240" : "ZS",
	"25282" : "FB",
	"25303" : "NA",
	"25324" : "KG",
	"25341" : "ZY",
	"25373" : "WZ",
	"25375" : "XJ",
	"25384" : "A",
	"25457" : "A",
	"25528" : "SD",
	"25530" : "SC",
	"25552" : "TD",
	"25774" : "ZC",
	"25874" : "ZC",
	"26044" : "YW",
	"26080" : "WM",
	"26292" : "PB",
	"26333" : "PB",
	"26355" : "ZY",
	"26366" : "CZ",
	"26397" : "ZC",
	"26399" : "QJ",
	"26415" : "ZS",
	"26451" : "SB",
	"26526" : "ZC",
	"26552" : "JG",
	"26561" : "TD",
	"26588" : "JG",
	"26597" : "CZ",
	"26629" : "ZS",
	"26638" : "YL",
	"26646" : "XQ",
	"26653" : "KG",
	"26657" : "XJ",
	"26727" : "HG",
	"26894" : "ZC",
	"26937" : "ZS",
	"26946" : "ZC",
	"26999" : "KJ",
	"27099" : "KJ",
	"27449" : "YQ",
	"27481" : "XS",
	"27542" : "ZS",
	"27663" : "ZS",
	"27748" : "TS",
	"27784" : "SC",
	"27788" : "ZD",
	"27795" : "TD",
	"27812" : "O",
	"27850" : "PB",
	"27852" : "MB",
	"27895" : "SL",
	"27898" : "PL",
	"27973" : "QJ",
	"27981" : "KH",
	"27986" : "HX",
	"27994" : "XJ",
	"28044" : "YC",
	"28065" : "WG",
	"28177" : "SM",
	"28267" : "QJ",
	"28291" : "KH",
	"28337" : "ZQ",
	"28463" : "TL",
	"28548" : "DC",
	"28601" : "TD",
	"28689" : "PB",
	"28805" : "JG",
	"28820" : "QG",
	"28846" : "PB",
	"28952" : "TD",
	"28975" : "ZC",
	"29100" : "A",
	"29325" : "QJ",
	"29575" : "SL",
	"29602" : "FB",
	"30010" : "TD",
	"30044" : "CX",
	"30058" : "PF",
	"30091" : "YSP",
	"30111" : "YN",
	"30229" : "XJ",
	"30427" : "SC",
	"30465" : "SX",
	"30631" : "YQ",
	"30655" : "QJ",
	"30684" : "QJG",
	"30707" : "SD",
	"30729" : "XH",
	"30796" : "LG",
	"30917" : "PB",
	"31074" : "NM",
	"31085" : "JZ",
	"31109" : "SC",
	"31181" : "ZC",
	"31192" : "MLB",
	"31293" : "JQ",
	"31400" : "YX",
	"31584" : "YJ",
	"31896" : "ZN",
	"31909" : "ZY",
	"31995" : "XJ",
	"32321" : "PF",
	"32327" : "ZY",
	"32418" : "HG",
	"32420" : "XQ",
	"32421" : "HG",
	"32438" : "LG",
	"32473" : "GJ",
	"32488" : "TD",
	"32521" : "QJ",
	"32527" : "PB",
	"32562" : "ZSQ",
	"32564" : "JZ",
	"32735" : "ZD",
	"32793" : "PB",
	"33071" : "PF",
	"33098" : "XL",
	"33100" : "YA",
	"33152" : "PB",
	"33261" : "CX",
	"33324" : "BP",
	"33333" : "TD",
	"33406" : "YA",
	"33426" : "WM",
	"33432" : "PB",
	"33445" : "JG",
	"33486" : "ZN",
	"33493" : "TS",
	"33507" : "QJ",
	"33540" : "QJ",
	"33544" : "ZC",
	"33564" : "XQ",
	"33617" : "YT",
	"33632" : "QJ",
	"33636" : "XH",
	"33637" : "YX",
	"33694" : "WG",
	"33705" : "PF",
	"33728" : "YW",
	"33882" : "SR",
	"34067" : "WM",
	"34074" : "YW",
	"34121" : "QJ",
	"34255" : "ZC",
	"34259" : "XL",
	"34425" : "JH",
	"34430" : "XH",
	"34485" : "KH",
	"34503" : "YS",
	"34532" : "HG",
	"34552" : "XS",
	"34558" : "YE",
	"34593" : "ZL",
	"34660" : "YQ",
	"34892" : "XH",
	"34928" : "SC",
	"34999" : "QJ",
	"35048" : "PB",
	"35059" : "SC",
	"35098" : "ZC",
	"35203" : "TQ",
	"35265" : "JX",
	"35299" : "JX",
	"35782" : "SZ",
	"35828" : "YS",
	"35830" : "E",
	"35843" : "TD",
	"35895" : "YG",
	"35977" : "MH",
	"36158" : "JG",
	"36228" : "QJ",
	"36426" : "XQ",
	"36466" : "DC",
	"36710" : "JC",
	"36711" : "ZYG",
	"36767" : "PB",
	"36866" : "SK",
	"36951" : "YW",
	"37034" : "YX",
	"37063" : "XH",
	"37218" : "ZC",
	"37325" : "ZC",
	"38063" : "PB",
	"38079" : "TD",
	"38085" : "QY",
	"38107" : "DC",
	"38116" : "TD",
	"38123" : "YD",
	"38224" : "HG",
	"38241" : "XTC",
	"38271" : "ZC",
	"38415" : "YE",
	"38426" : "KH",
	"38461" : "YD",
	"38463" : "AE",
	"38466" : "PB",
	"38477" : "XJ",
	"38518" : "YT",
	"38551" : "WK",
	"38585" : "ZC",
	"38704" : "XS",
	"38739" : "LJ",
	"38761" : "GJ",
	"38808" : "SQ",
	"39048" : "JG",
	"39049" : "XJ",
	"39052" : "HG",
	"39076" : "CZ",
	"39271" : "XT",
	"39534" : "TD",
	"39552" : "TD",
	"39584" : "PB",
	"39647" : "SB",
	"39730" : "LG",
	"39748" : "TPB",
	"40109" : "ZQ",
	"40479" : "ND",
	"40516" : "HG",
	"40536" : "HG",
	"40583" : "QJ",
	"40765" : "YQ",
	"40784" : "QJ",
	"40840" : "YK",
	"40863" : "QJG"
};

//é¡µé¢ç­å¾çjs
var t_id;
var pos = 0;
var dir = 2;
var len = 0;
function animate() {
var elem = document.getElementById('progress');
if(elem != null) {
if (pos == 0) len += dir;
if (len > 32 || pos > 99) pos += dir;
if (pos > 99) len -= dir;
if (pos > 99 && len == 0) pos = 0;
elem.style.left = pos;
elem.style.width = len;
}
}
function remove_loading() {
this.clearInterval(t_id);
var targelem = document.getElementById('loader_container');
targelem.style.display = 'none';
targelem.style.visibility = 'hidden';
} 

function clear_form(ff){
    var elements = ff.elements;
    for(i=0;i<elements.length;i++){
        var element = elements[i];
        if(element.type=="text"){
            element.value = "";
        }else if(element.type=="radio" || element.type=="checkbox"){
        	element.checked = false;
        }else if(element.options!=null){
        	element.options[0].selected  = true;
        }
    }
}
function loading_wait(){
	var o = document.getElementById('loader_wait');
	o.innerHTML="<div id='loader_container'><div id='loader'><div align='center'>é¡µé¢æ­£å¨å è½½ä¸­ ...è¯·ç¨å</div><div id='loader_bg'><div id='progress'> </div></div></div></div>";
	t_id = setInterval(animate,20)
}

var target;
var autoSubmit = false;
function   showTable()   
{ 
	var div = document.all.mydate;
	if(div!=null)
		return false;
	div = document.createElement("div");
	div.id = "mydate";
	div.style.display = "";
	div.style.position = "absolute";
	div.style.zIndex = "20";
	var html = "";
html += ("	 <table   width=200 style='font-size:12px;font-face:Arial'  border='0'   cellspacing='0'   style='border:1px   solid   #0066FF;   background-color:#EDF2FC;filter:\"progid:DXImageTransform.Microsoft.Shadow(direction=135,color=#999999,strength=3)\"'>");   
html += ("	 <tr>");   
html += ("	 <td   colspan='3'   align='center'     style='border-bottom:1px   solid   #0066FF;   background-color:#C7D8FA   ;font-family:Verdana;   font-size:12px'>");   
html += ("	 <input   type='button'   name='minus'   value='   -   '   style='height:18'     onClick='minus()'>   <input   type='text'   name='selectYear'   size='4'   value=''   style='height=18'>   <input   type='button'   name='add'   value='   +   '   style='height:18'   onClick='add()'>");   
html += ("	 </td>");   
html += ("	 <td   style='border-bottom:1px   solid   #0066FF;   background-color:#C7D8FA;   font-weight:bold;   font-family:Wingdings   2,Wingdings,Webdings;   font-size:16px;   padding-top:2px;   color:#4477FF;   cursor:hand'   align='center'   title='å³é­'   onClick='javascript:divClose()'>");   
html += ("	 <img border='0' src='/images/close.gif'>");   
html += ("	 </td>");   
html += ("	 </tr>");   
html += ("	 <tr>");   
html += ("	 <td   align='center'   onClick=\"setYear('01')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"     class=\"month\">1æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('02')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"     class=\"month\">2æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('03')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"     onmouseout=\"this.style.backgroundColor='#EDF2FC'\"     class=\"month\">3æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('04')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"     class=\"month\">4æ</td>");   
html += ("	 </tr>");   
html += ("	 <tr>");   
html += ("	 <td   align='center'   onClick=\"setYear('05')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">5æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('06')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"     class=\"month\">6æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('07')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">7æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('08')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">8æ</td>");   
html += ("	 </tr>");   
html += ("	 <tr>");   
html += ("	 <td   align='center'   onClick=\"setYear('09')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">9æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('10')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">10æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('11')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">11æ</td>");   
html += ("	 <td   align='center'   onClick=\"setYear('12')\"   onmouseover=\"this.style.backgroundColor='#4A83E1'\"   onmouseout=\"this.style.backgroundColor='#EDF2FC'\"   class=\"month\">12æ</td>");   
html += ("	 </tr>");   
html += ("	 </table>");   
div.innerHTML = html; 
document.body.appendChild(div);
}   
function   show_month(obj,flag)   
{   
	target = obj;
showTable();   
var minical = document.all.mydate;   
var x, y;				

x = (document.layers) ? loc.pageX : event.clientX;
y = (document.layers) ? loc.pageY : event.clientY;
autoSubmit = flag;
minical.style.top	= y+10;
minical.style.left	= x-10;
minical.style.display = (minical.style.display == "block") ? "none" : "block";   
init();   
}   
function   init()   
{   
      var   now   =   new   Date();   
      var   nowYear   =   now.getYear();  
      document.all.selectYear.value   =   nowYear;   
}   
function   minus()   
{   
        var   year   =   parseInt(document.all.selectYear.value)-1;   
if(year<1900)   
{   
alert("å¹´ä»½éæ©ä¸åç");   
return;   
}   
document.all.selectYear.value=year;   
}   
function   add()   
{   
        var   year   =   parseInt(document.all.selectYear.value)+1;   
if(year>2100)   
{   
        alert("å¹´ä»½éæ©ä¸åç");   
return;   
}   
document.all.selectYear.value=year;   
}   
function   divClose()   
{   
        document.getElementById("mydate").style.display="none";   
}   
function   setYear(year)   
{   
        target.value=document.all.selectYear.value+"."+year;   
        if(autoSubmit){
        	target.form.onsubmit();
        }
        autoSubmit = false;
divClose();   
}  

function ltrim(s){ 
	return s.replace( /^\s*/, ""); 
}
function rtrim(s){ 
	return s.replace( /\s*$/, ""); 
} 
function trim(s){ 
return rtrim(ltrim(s)); 
}

	function showCurrTime(){
		var Digital=new Date();
		var hours=Digital.getHours();
		var minutes=Digital.getMinutes();
		var seconds=Digital.getSeconds();
		if(minutes<=9)
			minutes="0"+minutes;
		if(seconds<=9)
			seconds="0"+seconds;
		myclock=""+hours+":"+minutes+":"+seconds;
		if(document.layers){
			document.layers.showTime.document.write(myclock);
		    document.layers.showTime.document.close();
		}else if(document.all)
		  document.all.showTime.innerHTML=myclock;
		setTimeout("showCurrTime()",1000);
	}
	
	/**
	 * Cookieçå¤ç
	 */
	var Cookies = {};
	/**
	 * è®¾ç½®Cookies
	 */
	Cookies.set = function(name, value){
	     var argv = arguments;
	     var argc = arguments.length;
	     var expires = (argc > 2) ? argv[2] : null;
	     var path = (argc > 3) ? argv[3] : '/';
	     var domain = (argc > 4) ? argv[4] : null;
	     var secure = (argc > 5) ? argv[5] : false;
	     document.cookie = name + "=" + escape (value) +
	       ((expires == null) ? "" : ("; expires=" + expires.toGMTString())) +
	       ((path == null) ? "" : ("; path=" + path)) +
	       ((domain == null) ? "" : ("; domain=" + domain)) +
	       ((secure == true) ? "; secure" : "");
	};
	/**
	 * è¯»åCookies
	 */
	Cookies.get = function(name){
	    var arg = name + "=";
	    var alen = arg.length;
	    var clen = document.cookie.length;
	    var i = 0;
	    var j = 0;
	    while(i < clen){
	        j = i + alen;
	        if (document.cookie.substring(i, j) == arg)
	            return Cookies.getCookieVal(j);
	        i = document.cookie.indexOf(" ", i) + 1;
	        if(i == 0)
	            break;
	    }
	    return null;
	};
	/**
	 * æ¸é¤Cookies
	 */
	Cookies.clear = function(name) {
	  if(Cookies.get(name)){
	    var expdate = new Date(); 
	    expdate.setTime(expdate.getTime() - (86400 * 1000 * 1)); 
	    Cookies.set(name, "", expdate); 
	  }
	};

	Cookies.getCookieVal = function(offset){
	   var endstr = document.cookie.indexOf(";", offset);
	   if(endstr == -1){
	       endstr = document.cookie.length;
	   }
	   return unescape(document.cookie.substring(offset, endstr));
	};
function fixWidth(percent, configedWidth){
	if(!configedWidth)
		configedWidth = 20;
	return parseInt(($("#pagination").width() - configedWidth) * percent);
}

function setClumWidth(width){
    var curWidth= document.body.clientWidth;
    return curWidth*width;
}

function ajaxReturnRefresh(){
	var currTab = parent.document.frames["frm"].getCurrTab();
   	var frmId = currTab[0].innerHTML.substring(11,currTab[0].innerHTML.length);
   	frmId = frmId.substring(0,frmId.indexOf(" "));
   	var frm = parent.document.frames["frm"].document.frames[frmId];
   	var frm1 = frm.document.frames["_right"];
   	if(frm1){
   		frm1.reloadDate();
   	}else
   		frm.reloadDate();	
}

function hidden_parent_scroll(){
	//alert($("#hideParentScroll").length+"   "+$("#hideParentScroll",parent.document).length);
	try{
		if($("#hideParentScroll").length=='0' && $("#hideParentScroll",parent.document).length=='0' && parent!=null){
			//alert($(parent.document).find("iframe").length);
			if($(parent.document).find("iframe").length>0){
				//alert("hello  ");
				$(parent.document.body).attr("style","overflow : hidden");
				//parent.document.body.scrolling = "no";
				//parent.document.body.style.overflow = "hidden";
			}			
		}	
	}catch(e){
		
	}
}
//window.attachEvent("onload",hidden_parent_scroll);

//$(document).ready(function(){
//	hidden_parent_scroll();
//});

function openLoginWin(){
	var p = parent;
	var i = 0;
	while(p.parent!=null){
		p = p.parent;
		if(p.frames.length>0){
			if($(p.frames["frm"]).length>0){
				break;
			}
		}
		i++;
		if(i>10)
			break;
	}
	if(i>10){
		var pos = this.location.href.indexOf("/jsp");
		window.open(this.location.href.substring(0,pos)+"/login1.jsp","_self");
	}else{
		var location = getCenterLocation(250,200);
		p.openWindow("loginWin", "登录", location.left, location.top, 250, 200, null, true,true,true,false,true);
		p.setImgScr("img1");
	}
}

/**
 * 向后台发送导出Excel请求
 * 
 * @param grid  页面数据区域DOM控件的ID
 * @param fileName 输出的文件名
 * @param colNames 需要导出的列，格式为"列1中文名|列1字段名,列2中文名|列2字段名"，如不穿的话表示从页面列表中读取所有的列
 * @param codeId 一维代码的id，多个以“,”隔开
 * @param codeFields 一维代码对应的字段名，多个以“,”隔开，且顺序与codeId一致
 * @param isAllData 是否导出所有数据，如果设置为false或者不设置只导出的话当前页面的数据
 */
function outputExcel(grid, fileName, colNames, codeId, codeFields, isAllData){
	var options = grid.datagrid('getPager').data("pagination").options;   
	var total = options.total;  //总记录数
	
	options = grid.datagrid("options");
	var url = options.url;
	
	
	if(!colNames || colNames == ""){
		var columns = options.columns[0];
		colNames = new Array();
		var j = 0;
		for(i=0;i<columns.length;i++){
			column = columns[i];
			if(column.title=='操作'||column.field=='id')
				continue;
			else{
				colNames[j] = column.title+"|"+column.field;
				j++;
			}
		}
	}
	
	
	var queryParams = options.queryParams;
	
	var str = "?";
	$.each(queryParams, function(key,value){
		str += key+"="+value+"&";
	});
	str += "rows="+total+"&";
	str += "outputType=excel&";
	str += "colNames="+encodeURIComponent(colNames)+"&";
	str += "fileName="+encodeURIComponent(fileName)+"&";
	str += "codeId="+codeId+"&";
	str += "codeFields="+codeFields;
	if(isAllData)
		str += "&isAllData="+isAllData;
	window.open("./"+url+str,'_blank');
}
function tabOnloadSuccess(){
}
function tabOnloadSuccess2(){
	tabOnloadSuccess();
}
function tabOnloadSuccess3(){
	tabOnloadSuccess();
}
/**
 * 向后台发送导出PDF请求
 * 
 * @param grid  页面数据区域DOM控件的ID
 * @param fileName 输出的文件名
 * @param colNames 需要导出的列，格式为"列1中文名|列1字段名,列2中文名|列2字段名"，如不穿的话表示从页面列表中读取所有的列
 * @param codeId 一维代码的id，多个以“,”隔开
 * @param codeFields 一维代码对应的字段名，多个以“,”隔开，且顺序与codeId一致
 * @param isAllData 是否导出所有数据，如果设置为false或者不设置只导出的话当前页面的数据
 */
function outputPDF(grid, fileName, colNames, codeId, codeFields, isAllData){
	var options = grid.datagrid('getPager').data("pagination").options;   
	var total = options.total;  //总记录数
	
	options = grid.datagrid("options");
	var url = options.url;
	
	if(!colNames || colNames == ""){
		var columns = options.columns[0];
		var colNames = new Array();
		var j = 0;
		for(i=0;i<columns.length;i++){
			column = columns[i];
			if(column.title=='操作'||column.field=='id')
				continue;
			else{
				colNames[j] = column.title+"|"+column.field;
				j++;
			}
		}
	}
	
	
	var queryParams = options.queryParams;
	
	var str = "?";
	$.each(queryParams, function(key,value){
		str += key+"="+value+"&";
	});
	str += "rows="+total+"&";
	str += "outputType=pdf&";
	str += "colNames="+colNames+"&";
	str += "fileName="+fileName+"&";
	str += "codeId="+codeId+"&";
	str += "codeFields="+codeFields;
	if(isAllData)
		str += "&isAllData="+isAllData;
	
	window.open("./"+url+str,'_blank');
}

/**
 * 2013/01/21
 * 修改Datagrid加载数据的方法以适应不同的浏览器
 * 
 */
function reloadData(id){
	var currTab=top.getCurrTab();
	currTab.panel('refresh');
	var windowId=id;
	if(windowId=="null")
		windowId=parent.$("#"+window.name).parent().attr("id");
	parent.close_win(windowId);
	
}

/**
 * 加载内容后根据内容大小调整窗口
 * 
 * @param windowId
 * @param frmId
 */
function autoAdjust(title, windowId, frmId){
	var mainheight = parseInt(parseInt($("#"+frmId).contents().find("table").height()) + parseInt(50));
	var mainwidth = parseInt(parseInt($("#"+frmId).contents().find("table").width()) + parseInt(15));
	
	if(!mainheight || !mainwidth || mainheight <= 50 || mainwidth <= 15){
		mainheight = $("#"+frmId).contents().find("div").height() + 50;
		mainwidth = $("#"+frmId).contents().find("div").width() + 15;
	}
	
	if(isNaN(mainheight)||isNaN(mainwidth)){
		
	}else{
	    if($("#"+frmId).attr("src")==""||$("#"+frmId).attr("src").indexOf("blank.html")!=-1)
	        return false;
		$("#"+frmId).width(mainwidth);
		$("#"+frmId).height(mainheight);
		
		var location = getCenterLocation(mainwidth + 15, mainheight + 50);
		
		
		$('#'+windowId).window({
		    title : title,
			width : mainwidth + 17,
			height : mainheight + 50,
			left : location.left,
			top : location.top,
			minimizable: false,
		    onBeforeClose:function(){
			    close_win(windowId);
		    }
		});
		$("#"+windowId).window('open');
	}
}

Date.prototype.format = function(format) //author: meizz 
{ 
  var o = { 
    "M+" : this.getMonth()+1, //month 
    "d+" : this.getDate(),    //day 
    "h+" : this.getHours(),   //hour 
    "m+" : this.getMinutes(), //minute 
    "s+" : this.getSeconds(), //second 
    "q+" : Math.floor((this.getMonth()+3)/3),  //quarter 
    "S" : this.getMilliseconds() //millisecond 
  } 
  if(/(y+)/.test(format)) format=format.replace(RegExp.$1, 
    (this.getFullYear()+"").substr(4 - RegExp.$1.length)); 
  for(var k in o)if(new RegExp("("+ k +")").test(format)) 
    format = format.replace(RegExp.$1, 
      RegExp.$1.length==1 ? o[k] : 
        ("00"+ o[k]).substr((""+ o[k]).length)); 
  return format; 
} 

/**
 * 当页面ready后，对当前页面中的form自动执行Validform的初始化
*/
$(function(){
	if($("body[validform=true] form").length==0)
		return;

	$("body[validform=true] form").Validform({
		"btnSubmit": "*[type=submit]",
		"tiptype": function(msg,o,cssctl){
			//msg：提示信息;
			//o:{obj:*,type:*,curform:*}, obj指向的是当前验证的表单元素（或表单对象），type指示提示的状态，值为1、2、3、4， 1：正在检测/提交数据，2：通过验证，3：验证失败，4：提示ignore状态, curform为当前form对象;
			//cssctl:内置的提示信息样式控制函数，该函数需传入两个参数：显示提示信息的对象 和 当前提示的状态（既形参o中的type）;

			if(!o.obj.is("form")){//验证表单元素时o.obj为该表单元素，全部验证通过提交表单时o.obj为该表单对象;
				var tip=$(o.obj).next(".validform_tip");
				if(tip.length==0)
					tip=$("<div class='validform_tip'><span class='Validform_checktip'></span><div class='validform_dec'><s class='validform_dec1'>&#9670;</s><s class='validform_dec2'>&#9670;</s></div></div>").insertAfter($(o.obj));
				
				var checktip=tip.find(".Validform_checktip").text(msg);
				cssctl(checktip,o.type);
				
				if(o.type==2){
					setTimeout(function(){
						tip.fadeOut(200);
					},2000);
				}else{
					tip.css({"display":"inline-block"});
				}
					
			}
		},
		"ajaxPost": $("body[validform=true] form").attr("ajax")||false,
		"callback": window.formAjaxCallback||null,
		"beforeSubmit": window.beforeSubmitCallback||null,
		"usePlugin":{
			passwordstrength:{
				minLen:6,
				maxLen:18
			}
		}
	});
});

function clear_form(ff){
	var elements = ff.elements;
	for(i=0;i<elements.length;i++){
		var element = elements[i];
		if(element.type=="text"){
			element.value = "";
		}else if(element.type=="radio" || element.type=="checkbox"){
			element.checked = false;
		}else if(element.options!=null){
			element.options[0].selected  = true;
		}
	}
}
$(function(){
	if($("#pagination").length==0)
		return;
	if (window.autoDatagridHeight) 
		window.datagridHeight="auto";
	else 
		window.datagridHeight=$(".submitdata").parent().height() - $(".submitdata").outerHeight(true)-20;
	window.dg_cm_pp={
		height: window.datagridHeight,
		striped: true,
		rownumbers:true,
		fitColumns:true,
		pagination:true,
		pageList:[10,20,30],
		onLoadSuccess:function(){
			$(window).trigger("resize");
		}
	}

});

$(window).resize(function() {
	var id = $(".TreeClass").attr("id");
	if(isStringNull(id)){
	$('#'+id).datagrid('resize',{
    	height: $(document).height(),
    	width: $(document).width()-10
	});
	}
});

function setImagePreview() {
	var docObj = document.getElementById("file");
	var imgObjPreview = document.getElementById("preview");
	if (docObj.files && docObj.files[0]) {
		// 火狐下，直接设img属性
		imgObjPreview.style.display = 'block';
		imgObjPreview.style.width = '178px';
		imgObjPreview.style.height = '20px';
		// imgObjPreview.src = docObj.files[0].getAsDataURL();
		// 火狐7以上版本不能用上面的getAsDataURL()方式获取，需要一下方式
		imgObjPreview.src = window.URL.createObjectURL(docObj.files[0]);
	} else {
		// IE下，使用滤镜
		docObj.select();
		// docObj.blur();
		window.parent.document.body.focus();
		var imgSrc = document.selection.createRange().text;
		var localImagId = document.getElementById("localImag");
		// 必须设置初始大小
		localImagId.style.width = "178px";
		localImagId.style.height = "20px";
		// 图片异常的捕捉，防止用户修改后缀来伪造图片
		try {
			localImagId.style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale)";
			localImagId.filters
					.item("DXImageTransform.Microsoft.AlphaImageLoader").src = imgSrc;
		} catch (e) {
			// alert("您上传的图片格式不正确，请重新选择!");
			return false;
		}
		localImagId.style.display = '';
		imgObjPreview.style.display = 'none';
		document.selection.empty();
	}
	return true;
}

 
function isNull(pram) 
{
	if(pram==null || typeof(pram)=="undefined")
	{
		return false;
	}
	return true
};
         String.prototype.Trim = function()  
         {  
             return this.replace(/(^\s*)|(\s*$)/g, "");  
        }  


function isStringNull(pram) 
{ 
	if(isNull(pram) &&  pram !=""  && pram.Trim()!='null' && pram.Trim()!='NULL')
	{
		return true;
	}
	return false
};
// 得到当选中的label的URL加上条件
function getFilterURL(selectCell, where)
{ 
	if (isStringNull(where) && selectCell != null)
	{ 
		var values = where.split(';');
		var filter = $(selectCell).attr("filter"); 
		if (values.length > 0 && filter.length > 0)
		{
			for (var j = 0; j < values.length; j++)
			{
				while (filter.indexOf('{' + j + '}') > 0) // 去掉所有的参数{0}{0}....
				{
					filter = filter.replace('{' + j + '}', values[j]);
				}
			}
			return getUrl($(selectCell).attr("url")) + filter;
		} else
		{
			return $(selectCell).attr("url");
		}
	}
	return '';
}

// 去掉默认的条件(用于label)
function getUrl(url)
{
	var params = url.split('&');
	for (i = 0; i < params.length; i++)
	{
		if (params[i].indexOf('filter=') == 0)
			return url.replace("&" + params[i], '');
	}
	return url;
}
//得到项目名称
var pathName=window.document.location.pathname;  
var ProjName=pathName.substring(0,pathName.substr(1).indexOf('/')+1); 
function GetXmlBySql(sql){
	 
 
	 var result;
	 $.ajax({
	                	url : ProjName+"/OpBySql.action",
	                	type: 'post',
	                    dataType: 'json',
	                    async : false,
	                    data:{ 
	                    	"sqlStr" : sql
	                    },
	                    success: function(data){
	                    	
	                        result =  data;
	                    }
	                });
	return result;
}
function IntoActionByUrl(url){
 	 var result;
	 $.ajax({
	                	url : url,
	                	type: 'post',
	                    dataType: 'json',
	                    async : false,
	                    error: function(){
	                    	$.messager.alert('错误','操作出错！');
	                    },
	                    success: function(data){
	                    	
	                        result =  data;
	                    }
	                });
	return result;
}
function IntoActionByUrl(url,params){
 	 var result;
	 $.ajax({
            	url : url,
            	type: 'post',
            	data: params,
                dataType: 'json',
                async : false,
                error: function(){
                	$.messager.alert('错误','操作出错！');
                },
                success: function(data){
                	
                    result =  data;
                }
            });
	return result;
}
//得到guid

function Page_GetGUID()
{
 
	 var result;
	 $.ajax({
    	url : ProjName+"/GetGuid.action",
    	type: 'post',
        dataType: 'json',
        async : false,
        success: function(data){
        	
            result =  data[0].guid;
        }
    });
	return result;
}
function	SetSelect(sql,SelectId,defaultId,param){
	$("#"+SelectId).empty();
	for(var i=0;i< param.length;i++){
		
      if(defaultId==param[i].split("=")[0]){
   	  	 $("#"+SelectId).append("<option value='"+param[i].split("=")[0]+"' selected >"+param[i].split("=")[1]+"</option>");
       }else{
  	    $("#"+SelectId).append("<option value='"+param[i].split("=")[0]+"'>"+param[i].split("=")[1]+"</option>");
	   }
	}
	 $.ajax({
	                	url : ProjName+"/OpSelectBySql.action",
	                	type: 'post',
	                    dataType: 'json',
	                    async : false,
	                    data:{ 
	                    	"sqlStr" : (sql),
	                    	"defaultId":defaultId
	                    },
	                    success: function(data){
	                    	$("#"+SelectId).append(data[0].OpStr);
	                    }
	                });
}
 
function closeAll(id){
	  window.location.reload();
	  $("#"+id).treegrid('collapseAll');
  }

function exportAll(id){ 
 
   $("#"+id).treegrid('expandAll');
     var intt=self.setInterval(function(){
          if($(".page_content").find(".datagrid-mask-msg").length == 0 ){
			window.clearInterval(intt);
			if($(".page_content").find(".tree-collapsed").length>0){
			exportAll(id)	
		}                   
		}
	},500);
 
  }
 function GetIndexFrame(currFrameId){
	return $("#"+currFrameId,parent.document.body)[0].contentWindow;
 }
function TreeGrid_RefreshNode(NodeId,TreeId){
 
		 var _data = {"2id":"11"}; 		    
		 $('#'+TreeId).treegrid('append',{  
        	 parent:NodeId,  // 这里指定父级标识就可以了  
        	 data: [_data] 
         });	
	
		$('#'+TreeId).treegrid('reload',NodeId);                        	
}
String.prototype.replaceAll = function(reallyDo, replaceWith, ignoreCase) {  
    if (!RegExp.prototype.isPrototypeOf(reallyDo)) {  
        return this.replace(new RegExp(reallyDo, (ignoreCase ? "gi": "g")), replaceWith);  
    } else {  
        return this.replace(reallyDo, replaceWith);  
    }  
}  

$.fn.extend({ 
  SubmitForm:function(url){ 
	var obj;
        var ajax_option={
						 
						url:url,
						type:"post", 
						dataType: "json",
						async : false,
						error: function(){
	                    	$.messager.alert('错误','保存时出错！');
	                    },
						success:function(data){
                                   obj=data;
						 }
						 }
						$(this).ajaxSubmit(ajax_option); 
                        return obj;  
  } 
}); 

 function DataEdit(pattern,MinDate,MaxDate){
	 var min="";
	 var max="";
	 var Str = new Object();
	 Str.dateFmt=pattern;
	 Str.onpicking = function(dp){$('#labelBottomDiv').css('display','')};
	 if(isStringNull(MinDate)){
		 Str.minDate="#F{$dp.$D(\'"+MinDate+"\')}";
	 }
	 if(isStringNull(MaxDate)){
		 Str.maxDate="#F{$dp.$D(\'"+MaxDate+"\')}";
	 }
	 WdatePicker(Str)
 }
 function SearchPage(frameName){
	 var currFrameId =  parent.frameElement.id; 
	  createSimpleWindow("addWindow","查找",ProjName+"/SearchByKeyWord.action?currFrameId="+currFrameId+"&frameName="+frameName, 400, 150);
 }
 function SearchByKeyWord(currFrameId,frameName){
	 var keyWord = $("#KeyWord").val();
	 var obj = GetIndexFrame(currFrameId).window.frames[frameName];
	  obj.findText(keyWord);
 }
 
function findText(keyWord)
{ 
            clearSelection();//先清空一下上次高亮显示的内容；
 
          $(":contains("+keyWord+")").each(function(){
        	  if($(this).children().length==0){
        		  $(this).html($(this).html().replace(keyWord, "<span class='highlight' style='background-color:yellow'>"+keyWord+"</span>")) ;
        	  }
        	  
          });
   
}
function clearSelection(){       
                
		$("body").find('.highlight').each(function()//找到所有highlight属性的元素；                
			{                 
			$(this).replaceWith($(this).html());//将他们的属性去掉；           
			});           
		         
}
   function SetValue(obj){
	   if(obj.checked){
		   obj.value="1";
	   }else{
		   obj.value="0";
	   }
	   $('#labelBottomDiv').css('display','');
   }
  function openw(DocId){
	  		  var width = "1000";
             if($(parent.window).width()<1000){
            	 width = $(parent.window).width()-100;
             }
    		 createSimpleWindow("viewDocWindow","查看文档",ProjName+"/km/km_upload/viewDoc.action?docId="+DocId+"&type=", width, $(parent.window).height()*0.8);
 
  }
 function openDoc(DocId){
	 var width = "1000";
     if($(parent.window).width()<1000){
    	 width = $(parent.window).width()-100;
     }
	 createSimpleWindow("viewDocWindow","查看文档",ProjName+"/km/km_upload/viewDoc.action?docId="+DocId+"&type=", width, $(parent.window).height());
  }

 //格式化金额  已，隔开
 function fmoney(s, n) {
	if(s != ""){
	    n = n > 0 && n <= 20 ? n : 2;  
	    s = parseFloat((s + "").replace(/[^\d\.-]/g, "")).toFixed(n) + "";  
	    var l = s.split(".")[0].split("").reverse(), r = s.split(".")[1];  
	    t = "";  
	    for (i = 0; i < l.length; i++) {  
	        t += l[i] + ((i + 1) % 3 == 0 && (i + 1) != l.length ? "," : "");  
	    }  
	    return t.split("").reverse().join("") + "." + r;
	}else{
		return "0.00";
	}
 }
 
 //将人民币转大写
 function convertCurrency(currencyDigits) { 
	// Constants: 
	var MAXIMUM_NUMBER = 99999999999.99; 
	// Predefine the radix characters and currency symbols for output: 
	var CN_ZERO = "零"; 
	var CN_ONE = "壹"; 
	var CN_TWO = "贰"; 
	var CN_THREE = "叁"; 
	var CN_FOUR = "肆"; 
	var CN_FIVE = "伍"; 
	var CN_SIX = "陆"; 
	var CN_SEVEN = "柒"; 
	var CN_EIGHT = "捌"; 
	var CN_NINE = "玖"; 
	var CN_TEN = "拾"; 
	var CN_HUNDRED = "佰"; 
	var CN_THOUSAND = "仟"; 
	var CN_TEN_THOUSAND = "万"; 
	var CN_HUNDRED_MILLION = "亿"; 
	var CN_SYMBOL = "人民币"; 
	var CN_DOLLAR = "元"; 
	var CN_TEN_CENT = "角"; 
	var CN_CENT = "分"; 
	var CN_INTEGER = "整"; 
	 
	// Variables: 
	var integral;    // Represent integral part of digit number. 
	var decimal;    // Represent decimal part of digit number. 
	var outputCharacters;    // The output result. 
	var parts; 
	var digits, radices, bigRadices, decimals; 
	var zeroCount; 
	var i, p, d; 
	var quotient, modulus; 
	 
	// Validate input string: 
	currencyDigits = currencyDigits.toString(); 
	if (currencyDigits == "") { 
		alert("请输入小写金额！"); 
		return ""; 
	} 
	if (currencyDigits.match(/[^,.\d]/) != null) { 
		alert("小写金额含有无效字符！"); 
		return ""; 
	} 
	if ((currencyDigits).match(/^((\d{1,3}(,\d{3})*(.((\d{3},)*\d{1,3}))?)|(\d+(.\d+)?))$/) == null) { 
		alert("小写金额的格式不正确！"); 
		return ""; 
	} 
	 
	// Normalize the format of input digits: 
	currencyDigits = currencyDigits.replace(/,/g, "");    // Remove comma delimiters. 
	currencyDigits = currencyDigits.replace(/^0+/, "");    // Trim zeros at the beginning. 
	// Assert the number is not greater than the maximum number. 
	if (Number(currencyDigits) > MAXIMUM_NUMBER) { 
	    alert("金额过大，应小于1000亿元！"); 
	    return ""; 
	} 
	 
	// Process the coversion from currency digits to characters: 
	// Separate integral and decimal parts before processing coversion: 
	parts = currencyDigits.split("."); 
	if (parts.length > 1) { 
	    integral = parts[0]; 
	    decimal = parts[1]; 
	    // Cut down redundant decimal digits that are after the second. 
	    decimal = decimal.substr(0, 2); 
	}else { 
	    integral = parts[0]; 
	    decimal = ""; 
	} 
	// Prepare the characters corresponding to the digits: 
	digits = new Array(CN_ZERO, CN_ONE, CN_TWO, CN_THREE, CN_FOUR, CN_FIVE, CN_SIX, CN_SEVEN, CN_EIGHT, CN_NINE); 
	radices = new Array("", CN_TEN, CN_HUNDRED, CN_THOUSAND); 
	bigRadices = new Array("", CN_TEN_THOUSAND, CN_HUNDRED_MILLION); 
	decimals = new Array(CN_TEN_CENT, CN_CENT); 
	// Start processing: 
	outputCharacters = ""; 
	// Process integral part if it is larger than 0: 
	if (Number(integral) > 0) { 
	    zeroCount = 0; 
	    for (i = 0; i < integral.length; i++) { 
	        p = integral.length - i - 1; 
	        d = integral.substr(i, 1); 
	        quotient = p / 4; 
	        modulus = p % 4; 
	        if (d == "0") { 
	            zeroCount++; 
	        } 
	        else { 
	            if (zeroCount > 0) 
	            { 
	                outputCharacters += digits[0]; 
	            } 
	            zeroCount = 0; 
	            outputCharacters += digits[Number(d)] + radices[modulus]; 
	        } 
	        if (modulus == 0 && zeroCount < 4) { 
	            outputCharacters += bigRadices[quotient]; 
	            zeroCount = 0; 
	        } 
	    } 
	    outputCharacters += CN_DOLLAR; 
	} 
	// Process decimal part if there is: 
	if (decimal != "") { 
	for (i = 0; i < decimal.length; i++) { 
	    d = decimal.substr(i, 1); 
	    if (d != "0") { 
	            outputCharacters += digits[Number(d)] + decimals[i]; 
	    } 
	    } 
	} 
	// Confirm and return the final output string: 
	if (outputCharacters == "") { 
		outputCharacters = CN_ZERO + CN_DOLLAR; 
	} 
	if (decimal == "") { 
        outputCharacters += CN_INTEGER; 
    } 
   // outputCharacters = CN_SYMBOL + outputCharacters; 
    return outputCharacters; 
} 
 
 
	
 /** 
 * 使用方法: 
 * 开启:MaskUtil.mask(); 
 * 关闭:MaskUtil.unmask(); 
 *  
 * MaskUtil.mask('其它提示文字...'); 
 */  
var MaskUtil = (function(){  
      
    var $mask,$maskMsg;  
      
    var defMsg = '正在处理，请稍待。。。';  
      
    function init(){  
        if(!$mask){  
            $mask = $("<div class=\"datagrid-mask mymask\"></div>").appendTo("body");  
        }  
        if(!$maskMsg){  
            $maskMsg = $("<div class=\"datagrid-mask-msg mymask\">"+defMsg+"</div>")  
                .appendTo("body").css({'font-size':'12px'});  
        }  
          
        $mask.css({width:"100%",height:$(document).height()});  
          
        var scrollTop = $(document.body).scrollTop();  
          
        $maskMsg.css({  
            left:( $(document.body).outerWidth(true) - 190 ) / 2  
            ,top:( ($(window).height() - 45) / 2 ) + scrollTop  
        });   
                  
    }  
      
    return {  
        mask:function(msg){  
            init();  
            $mask.show();  
            $maskMsg.html(msg||defMsg).show();  
        }  
        ,unmask:function(){  
            $mask.hide();  
            $maskMsg.hide();  
        }  
    }  
      
}());  
 